### PR TITLE
Schema Fingerprints

### PR DESCRIPTION
**Pull request by michal-harish**

### CODE REVIEW

**Comment by behdadforghani** [comment]
Schema needs to be converted to canonical form before fingerprint calculations as explained in https://avro.apache.org/docs/1.8.1/spec.html#Schema+Fingerprints.
For example, rule [FULLNAMES] specifies that all names need to be expanded to namespace.name.

**Comment by michal-harish** [comment]
I was aiming for that hence introduced in the `schema.go` a new method for all schema types:
```
        // Canonical formatter
	MarshalJSON() ([]byte, error)
```
However `MarshalJSON()` already existed for `RecordSchema` I didn't modify it yet.

So the question is: keep the existing MarshalJSON implementations and introduce new `MarshalCannonicalJSON()` or change the output of MarshalJSON for RecordSchema?

**Comment by behdadforghani** [comment]
My personal opinion is to create MarshalCanonicalJSON because canonical schema drops information such as default. I.e., it will contain less information than the original schema.

**Comment by michal-harish** [comment]
Had to go with Schema.Canonical() that returns type CanonicalSchema because of recursive nature. CanonicalSchema then has a method MarshalJSON that is used in the Fingerprint. The default values are stripped although it is arguable whether the field with and without default is canonically same. Because for example for evolution purpose they are different. The avro spec implies to strip defaults as well.

**Comment by michal-harish** [comment]
Closing - made too many changes in the fork since this was opened

**Pull request closed without merging**
